driver:driverSingleLL.o apiSingleLL.o insertSingleLL.h
	cc -o driver driverSingleLL.o apiSingleLL.o insertSingleLL.h 
driverSingleLL.o:driverSingleLL.c
	cc -c driverSingleLL.c
apiSingleLL.o:apiSingleLL.c
	cc -c apiSingleLL.c
clean:
	rm driverSingleLL.o apiSingleLL.o
